### ISSUE TITLE
About image resolution and optical flow resolution

### ISSUE THREAD

**Issue by 1129ljc** [hitachinsk/FGT#12]
I noticed that in the code './tool/video_inpainting. Py 'the resolution of the optical flow estimation for low-resolution images is extended, which causes the resolution to not align when the function rf.regionfill() is called.
`if imgH < 350:
        flowH, flowW = imgH * 2, imgW * 2
    else:
        flowH, flowW = imgH, imgW`
After this code is deleted, the sample is generated accurately. Can the author explain the reason for this?v

**Comment by hitachinsk** [comment]
That may be a bug after refactor, I will check the details. The usage about these two lines is to estimate accurate optical flows. Since we adopt RAFT for flow estimation, we noticed the performance of deep learning-based optical flow estimation methods is related to the frame resolution. If the resolution is too low, the performance of flow estimation will degrade. Therefore, we enlarge the frame resolution when the resolution is too low.

**Comment by hitachinsk** [comment]
This bug is fixed, I impose the resize operations to optical flows in `calculate_flow` function in the code `./tool/video_inpainting.py`.
