### ISSUE TITLE
How can I test a custom video? I have only any video.

### ISSUE THREAD

**Issue by umitkacar** [hitachinsk/FGT#17]
Your study is brilliant!

I would like to try a custom video. Do we need a mask for any video? If yes, what do you suggest for this?

Will you release any demo like this scenario? (I have only any video)

Thank you.

**Comment by hitachinsk** [comment]
Currently, our method (FGT) needs masks for each frame in the video to indicate the regions we want to remove. If you only have videos, you can utilize the interactive video segmentation tools to generate the masks for the videos. Due to the rapid progress of this field, you can generate satisfying masks for each video with an excellent tool and some manual modifications.

Here are some excellent interactive video segmentation tools.
- https://github.com/hkchengrex/MiVOS
- https://github.com/Limingxing00/RDE-VOS-CVPR2022

**Comment by hitachinsk** [comment]
By the way, I also noticed some of the "semi-supervised" video inpainting methods, which claims they can generate the masks and  inpainting the masked regions in a unified framework. However, I think such method is not flexible compared with the "segmentation + inpainting" workflow. Therefore, I still recommend to generate the masks with an explicit segmentation tool but not the "semi-supervised" video inpainting methods.

**Comment by umitkacar** [comment]
Thank you for your recommendations. I will try these.
