### ISSUE TITLE
Can't be cleaned up, is it an issue with the pre-trained model?

### ISSUE THREAD

**Issue by wxllyf** [hitachinsk/FGT#43]
FGT 
![微信截图_20231007121612](https://github.com/hitachinsk/FGT/assets/1106791/e7c016ba-e237-4c4c-afdf-cd388970b0e7)

other 
![微信截图_20231007121405](https://github.com/hitachinsk/FGT/assets/1106791/4b1cd147-df54-4a79-83ee-1230df762018)

What steps have I missed? To shorten the training time, can I train only on the sequence frames of a single video?

**Comment by hitachinsk** [comment]
To use FGT model, you should provide a mask to indicate the regions you want to remove, otherwise the model cannot know which region should be removed. Moreover, FGT cannot be trained with a single video because the model needs more data to achieve a better result.

**Comment by wxllyf** [comment]
Both screenshots use the same frames and masks, so it feels strange. I learned about FGT from recommendations in the comments of another project.
Below is the original image.
![微信截图_20231007163306](https://github.com/hitachinsk/FGT/assets/1106791/e164732e-7f62-4d8f-b3b1-299410811e81)

The command I used is:python video_inpainting.py --path images --path_mask  masks --outroot  test  --imgH 512 --imgW 288

**Comment by hitachinsk** [comment]
It's so strange, because the original content is left in the inpainted frame. If the mask covers **all the content in all the frames**, the unwanted content should not present in the result. Since FGT propagates the content across all the frames in the videos, please check the masks across all the frames carefully. I think some of the content are not be covered in some of the frames, therefore the result degrades.

**Comment by wxllyf** [comment]
> Reference in

Thank you very much, I will compare and compare what went wrong.
